name: Restrict Pull Requests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  restrict-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR source
        run: |
          echo "Checking PR from ${{ github.head_ref }} to ${{ github.base_ref }}"
          if [[ "${{ github.base_ref }}" == "develop" ]]; then
            [[ "${{ github.head_ref }}" =~ ^(feature/frontend|feature/backend|feature/devops)$ ]] || {
              echo "❌ Seules les branches front, back, devops peuvent faire des PR vers develop.";
              exit 1;
            }
          elif [[ "${{ github.base_ref }}" == "main" ]]; then
            [[ "${{ github.head_ref }}" == "develop" ]] || {
              echo "❌ Seule la branche develop peut faire une PR vers main.";
              exit 1;
            }
          fi